### PR TITLE
Allow users to rename Zones

### LINKED ISSUE #194: Allow users to rename `Zones`
Extension of #181

### LINKED ISSUE #195: Stop Using `QTreeWidget` for `ZoneList`
Using `QTreeWidget` wasn't a very smart idea to begin with and lead to some technical debt. This change should help with the implementation of #194

### PR DESCRIPTION
**Pull request by BryceBeagle**
Resolves #194 

Review along with #196 which resolves #195 

TODO: 
- [x] Don't allow a user to rename a `Zone` to "Screen"

Feedback on whether this is intuitive enough would be appreciated

### CODE REVIEW

**Review by velovix — CHANGES_REQUESTED** [review]
I'm not sure if this is just me, but it looks like the name only becomes a text box if I know to click the zone name text. I think this would be very intuitive if it were just always a text box when editing the zone.

**Comment by BryceBeagle** [comment]
That's a reasonable suggestion. Would you have the name still double-clickable when not explicitly editing the Zone?

**Comment by velovix** [comment]
I don't think that's necessary. Having to press the pencil to edit the zone makes sense to me.

**Comment by velovix** [comment]
Bryce and I decided it was chill to just have a bit of text saying to double click the zone name to change it. Not quite ideal yet, but we'll get there in the future.

**Comment by apockill** [comment]
Deleting a zone still causes a visual artifact:
visual-artifact

**Review by apockill — APPROVED** [review]
LGTM!

**Comment by BryceBeagle** [comment]
@velovix should we make the dark theme pencil icon consistent in this PR before merge, or in another PR?

**Review by apockill — CHANGES_REQUESTED** [review]
Wait no, it's buggy

**Comment by BryceBeagle** [comment]
Issue with duplicated Alarm widgets should be resolved now

**Comment by velovix** [comment]
@BryceBeagle Yeah I'll give it a little bit of a fix

**Comment by velovix** [comment]
Okay, the "shine" of the pencil should now be transparent instead of white.

**Review by apockill — APPROVED** [review]
Everything seems to work!

**Pull request merged**
